apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodewebapp
  name: nodewebapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodewebapp
  strategy: {}
  template:
    metadata:
      labels:
        app: nodewebapp
    spec:
      containers:
      - image: gdevtestex/test:latest
        name: test
        resources: {}
        ports:
        - containerPort: 3000
status: {}

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nodewebapp-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nodewebapp
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

---
apiVersion: v1
kind: Service
metadata:
  name: nodewebapp-service
spec:
  selector:
    app: nodewebapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nodewebapp-ingress
spec:
  rules:
  - host: test.gcg.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nodewebapp-service
            port:
              number: 80
