apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodewebapp
  name: nodewebapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodewebapp
  strategy: {}
  template:
    metadata:
      labels:
        app: nodewebapp
    spec:
      containers:
      - image: gdevtestex/test:latest
        name: test
        resources: {}
        ports:
        - containerPort: 3000
        env:
        - name: MONGODB_URI
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MONGODB_URI
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: PORT
status: {}

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nodewebapp-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nodewebapp
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

---
apiVersion: v1
kind: Service
metadata:
  name: nodewebapp-service
spec:
  selector:
    app: nodewebapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nodewebapp-ingress
spec:
  rules:
  - host: test.gcg.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nodewebapp-service
            port:
              number: 80

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  MONGODB_URI: "mongodb://mongodb-service:27017"
  PORT: "3000"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mongodb

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongodb-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
